[package]
name = "wasmhub-rust-runtime"
version = "1.82.0"
edition = "2021"

[[bin]]
name = "rust-runtime"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
